site/src/analytics-integrations.ts
Add a list of ignored domains to hide from the integrations table.
As a start, the  "frontend" integration and all it's dependencies (and sub-deps) are added 
<https://github.com/home-assistant/core/blob/dev/homeassistant/components/frontend/manifest.json>
=> Add a list of ignored domains

site/src/data.ts, worker/src/data.ts, worker/src/handlers/get.ts, worker/src/handlers/post.ts, worker/src/handlers/schedule.ts
Docs: https://github.com/home-assistant/home-assistant.io/pull/17232
=> Store the origin country-code

site/src/analytics-integrations.ts
Integration percentage rounded to 1 decimal looks better than just 0% and percentage of instalations is also rounded to 1 decimal.
=> Round integration percentage to 1 decimal

.gitignore, script/build, script/develop, site/src/data.ts
Limit request to the doc site by storing a copy of `integrations.json` on build
=> Store a copy of the integration details

site/src/analytics-map.ts, worker/src/data.ts, worker/src/handlers/post.ts, worker/src/utils/validate.ts
Docs https://github.com/home-assistant/home-assistant.io/pull/17440
=> Use regionCode (state) for US

script/build, script/develop, site/public/_headers
Since we are downloading this on build, this rule is no longer needed.
=> Remove header rule

site/src/analytics-average.ts
This it what we can see on the page https://analytics.home-assistant.io/#statistics :
It is not clear what does this number mean. It is 1.6 users or 2.9 ?
In this PR I've changed the way that number is shown:
Now it is clear how many users are there on average.
On that page there are several more numbers:
* Average integrations — 76
* Average entities — 287
* Average automations — 33
But that numbers are pretty big, so I don't feel that there should be a fractional part for them. That's why I've left them untouched.
=> Showing average users number with two decimal places

worker/src/data.ts, worker/src/handlers/schedule.ts, worker/src/utils/group-versions.ts, worker/tests/utils/group-versions.spec.ts
At the moment, we don't store any history information for `versions`. That is unfortunate as it prevents us from showing any time based changes aside from the current distribution.
With this PR a grouped version count will be added to each new history entry. The algorithm is the one currently used to display the `Last releases` chart.
This will enable us to show a graph of the version history similar to the one for `Active Installations` => #219
=> Add grouped version data to history

site/src/analytics-version-history.ts
Currently `Last releases` uses descending ordering whereas the `Version history` uses ascending ordering. The result is that the colors between the pi chart and the graph don't match up.
This PR reverses the ordering for the `Version history`.
=> Version history - reverse ordering to match `Last releases`

site/src/add-ons.html
"Z-Wave JS to MQTT" is now known as "Z-Wave JS UI". 
See: https://github.com/hassio-addons/repository/commit/e85db0e78c03994a17fe723fee60164469427ac2
=> Rename Z-Wave JS UI addon

site/.eleventy.js
Removes the starting "r" of "rdata" in the key for defining the "data" for the Container version graph, this additional "r" makes it so it currently does not show on the graph as it expects the key tp be "data".
=> Remove r from rdata key for Container version graph

worker/src/data.ts, worker/src/handlers/schedule.ts
This reverts the change of #668.
Instead of that approach, this adds a local variable that will subtract the number of calls done by listing out the entries.
(count / 1000) as it lists 1000 pr call.
The API should be able to handle 1000 invocations, so with this, we might be able to push it up to 900/950 in the future.
Note: This is a "band-aid" fix as well as #668 was, even with this we will still see issues when we get > 800K, but I have a plan for that which can be implemented later.
=> Adjust max worker invocation value

worker/src/data.ts, worker/src/handlers/schedule.ts, worker/src/utils/validate.ts, worker/tests/utils/validate.spec.ts
Allow the payload to be extended to include entries like:
```json
...
"recorder":{"engine":"sqlite","version":"123"},
...
```
=> Allow recorder engine in payload

site/.eleventy.js
As boards can be anything, we should only show boards with a defined friendly name.
=> Only show boards with friendly name

.github/workflows/test.yaml, .github/workflows/worker.yaml, package.json, script/worker_build, script/worker_develop, script/worker_publish, worker/wrangler.toml, yarn.lock
V1 is deprecated and should no longer be used.
This PR updates wrangler to v3 (3.5.1)
=> Update wrangler from v1 to v3

worker/src/utils/group-versions.ts, worker/tests/handlers/schedule.spec.ts, worker/tests/utils/group-versions.spec.ts
On dev we currently only have versions for 2021 (these were injected without TTL to ensure test data).
<https://dev--home-assistant-analytics.netlify.app/>
Using 10 for dev _should_ show more versions going forward.
=> Use 10 as cutoff for version filter on dev

package.json, worker/src/handlers/post.ts, worker/src/handlers/schedule.ts, worker/src/index.ts, yarn.lock
Replaces #777 
As that is a breaking change, the required changes is handled in this PR.
=> Bump toucan.js from 2.6.1 to 3.3.0

site/src/_layouts/base.html
Ideally we would have a large graphic to be used here and for `og:image`,
But for now lets just set this to "summary", which closes #639
=> Change twitter:card from summary_large_image to summary

worker/src/handlers/post.ts, worker/src/handlers/schedule.ts, worker/src/index.ts, worker/tests/handlers/post.spec.ts, worker/tests/handlers/schedule.spec.ts, worker/tests/mock.ts
Before v3 of tucan-js the context was included in the event, when doing the migration I forgot about adding that back.
This PR also adds the `cf-ray` header.
=> Add event context and cf-ray to sentry

worker/src/data.ts, worker/src/handlers/post.ts, worker/src/handlers/schedule.ts, worker/src/index.ts, worker/src/utils/group-versions.ts, worker/tests/handlers/post.spec.ts, worker/tests/handlers/schedule.spec.ts, worker/tests/mock.ts, worker/tests/utils/group-versions.spec.ts
A while back Cloudflare changed how workers should be defined from the old style event listener to the new exported handler.
This PR migrates the worker in this repository to the new style.
=> Refactor worker entrypoint

site/src/statistics.html
Since the change in how integrations are reported, this number has shown an incorrect (impossible) value.
=> Fix energy configured calculation

worker/src/data.ts, worker/src/handlers/schedule.ts, worker/wrangler.toml
We are sometimes hitting CPU limits, I think that is related to the time it can take when trigger the site build.
So as an attempt to mitigate the problem, that part has been extracted to its own schedule.
=> Move site generation to a separate schedule

site/src/tools/friendly_names.js
New board for HAOS 12.0
https://github.com/home-assistant/operating-system/releases/tag/12.0.rc1
=> Add Odroid-M1S to board names

site/src/index.html
This adds a small (responsive) introduction to the analytics website.
=> Add an introduction to analytics website

site/src/prometheus/addons.liquid, site/src/prometheus/base.liquid, site/src/prometheus/custom_integrations.liquid, site/src/prometheus/integrations.liquid
These "endpoints" can be used for the Prometheus scraper and graphed directly or in tools like Grafana.
Im not really sure how useful this is, personally, I want this data, but I could also run a Prometheus exporter locally with this.
=> Add "endpoints" with prometheus compatible metrics

site/src/add-ons.html
Assist Microphone has been added to the core add-ons, so I thought I'd add it to the analytics view as well.
=> Add Assist Microphone to core add-ons list

.github/workflows/test.yaml, .github/workflows/worker.yaml
So, while we can have the same outcome by changing the repository setting for it, as read is now applied to all workflows.
That setting does not apply to forks.
=> Add permissions to workflows

site/src/index.html
Related to https://github.com/home-assistant/analytics.home-assistant.io/pull/964 PR by @balloob 
Changed "_a fourth_" to intead say "_**less than less than a fourth**_" to make the "2-million" estimate hold true -> https://www.home-assistant.io/blog/2025/04/16/state-of-the-open-home-recap/ 
At least based on based on current analytics which at this date "only" lists 478,363 Active Home Assistant Installations so does not quite make 2-million as of yet -> https://analytics.home-assistant.io
=> forth -> less than a fourth
