home-assistant/analytics.home-assistant.io

- site/index.html
- site/src/analytics-integrations.ts
- site/src/data.ts
- Concat integration list from the doc site to indicate "unused" integrations.
- Use the title from the doc site if any
- Add filter and index to integration list
> Add search and friendly name to integration table

- site/src/analytics-active-installations.ts
> Change axis title colors

- site/src/analytics-active-installations.ts
- site/src/analytics-average.ts
- site/src/analytics-element.ts
- site/src/analytics-installation-types.ts
- site/src/analytics-versions.ts
Alternative to https://github.com/home-assistant/analytics.home-assistant.io/pull/32
> Alternative layout for installation types

- worker/src/handlers/schedule.ts
We only need to store the things we graph in the main object.
In case we want to change it up later, everything will be stored as `history:${timestampString}`
> Limit data in the generated payload

- worker/src/data.ts
- worker/src/handlers/post.ts
- worker/src/handlers/schedule.ts
- worker/wrangler.toml
For https://github.com/home-assistant/core/pull/48742
> Use uuid instead of huuid

- README.md
- site/src/analytics-element.ts
> Use main docsite for URL's

- site/src/analytics-element.ts
Or do we want to highlight it even more:
> Typo + color issue message

- worker/src/data.ts
- worker/src/handlers/post.ts
- worker/src/index.ts
- worker/src/utils/validate.ts
Followup to <https://github.com/home-assistant/analytics.home-assistant.io/pull/95#discussion_r614129339>
> Use create instead of assert for validation

- README.md
- site/src/analytics-active-installations.ts
- site/src/analytics-average.ts
- site/src/analytics-element.ts
- site/src/analytics-installation-types.ts
- site/src/analytics-integrations.ts
- site/src/analytics-map.ts
- site/src/analytics-versions.ts
- site/src/data.ts
- site/tsconfig.json
- worker/src/data.ts
- worker/src/handlers/post.ts
- worker/src/handlers/schedule.ts
- worker/src/index.ts
- worker/src/utils/migrate.ts
- worker/tests/handlers/post.spec.ts
- worker/tests/handlers/schedule.spec.ts
- worker/tests/mock.ts
- worker/tests/utils/migrate.spec.ts
- worker/wrangler.toml
The format of KV_KEY_CORE_ANALYTICS will change, so this will break anything that uses our data.json file
> Add multiple scheduled tasks

- worker/src/utils/validate.ts
- worker/tests/utils/validate.spec.ts
For https://github.com/home-assistant/core/pull/49725
> Allow operating_system in the payload

- worker/src/handlers/schedule.ts
https://sentry.io/organizations/home-assistant-io/issues/2369277398/?project=5720298&query=is%3Aunresolved
> Fix amount of API calls while handling missing metadata

- site/src/analytics-os-boards.ts
- worker/src/data.ts
- worker/src/handlers/schedule.ts
- worker/tests/handlers/schedule.spec.ts
- Use https://version.home-assistant.io/dev.json to limit OS boards to known names
- Add friendly name for rpi0-w
> Limit to known boards

- site/src/analytics-average.ts
- site/src/analytics-integrations.ts
> Show percentage of installations which shared integrations and statistics data

- site/src/analytics-element.ts
- site/src/analytics-version-history.ts
Depends on #218
Add graph to display version history.
> Add version history graph

- package.json
- yarn.lock
The map highlights countries with 1 instance ([Screenshot](https://discord.com/channels/330944238910963714/351047592588869643/870764539816341514)). This is an issue with svgmap 2.3.0 and is fixed in 2.3.1.
Dependabot bumped svgmap to 2.5.2 in the dev branch. So the dev branch should be merged into main.
> Merge dev to main

- worker/src/data.ts
- worker/src/handlers/schedule.ts
- worker/src/utils/validate.ts
- worker/tests/utils/validate.spec.ts
Needed for https://github.com/home-assistant/core/pull/53855
> Add energy analytics

- site/src/analytics-active-installations.ts
- site/src/analytics-version-history.ts
> Change gridline color for darkmode

- site/src/analytics-integrations.ts
> Show 0 decimal

- site/src/analytics-element.ts
- site/src/analytics-header.ts
- site/src/analytics-integrations.ts
Use the value from `?domain=[domain]#integrations` to initialize the filter on the integrations tab if present 
https://deploy-preview-294--home-assistant-analytics.netlify.app/?domain=esphome#integrations
if the requested integration is hidden by default (default/internal), the `_showDefaultAndInternal` property is set to `true` 
https://deploy-preview-294--home-assistant-analytics.netlify.app/?domain=analytics#integrations
> Get search from URL

- package.json
- site/src/analytics-active-installations.ts
- site/src/analytics-average.ts
- site/src/analytics-element.ts
- site/src/analytics-header.ts
- site/src/analytics-installation-types.ts
- site/src/analytics-integrations.ts
- site/src/analytics-map.ts
- site/src/analytics-os-boards.ts
- site/src/analytics-os-versions.ts
- site/src/analytics-releases.ts
- site/src/analytics-version-history.ts
- site/src/components/analytics-chart.ts
- yarn.lock
https://deploy-preview-348--home-assistant-analytics.netlify.app/
> Migrate to Lit 2

- site/src/analytics-addons.ts
Needs: <https://github.com/home-assistant/supervisor/pull/3430>
> Add new ESPHome add-on repo

- worker/src/data.ts
- worker/src/handlers/schedule.ts
- worker/src/utils/validate.ts
- worker/tests/utils/validate.spec.ts
For https://github.com/home-assistant/core/pull/68254
> Add handling for certificate in the payload

- site/src/analytics-addons.ts
- site/src/analytics-integrations.ts
> Remove clear btn position

- site/src/analytics-addons.ts
Update ESPHome addon repository
> Remove community ESPHome addon

- package.json
- site/.eleventy.js
- worker/src/data.ts
- worker/src/handlers/schedule.ts
- yarn.lock
Release reduction of queue size to workaround API limit.
> Release Dec 6

- package.json
- site/.eleventy.js
- site/src/index.html
- yarn.lock
> Bump chart.js from 3.9.1 to 4.0.1

- .github/workflows/test.yaml
- .github/workflows/worker.yaml
Similar to home-assistant/services.home-assistant.io#413 and the adjustment in home-assistant/services.home-assistant.io#414
> Use NodeJS version defined in .nvmrc for actions

- .github/workflows/test.yaml
- .github/workflows/worker.yaml
Same as https://github.com/home-assistant/services.home-assistant.io/pull/412
> Use wrangler version from package.json in actions

- site/src/tools/colors.js
> Adjust color generation

- site/src/index.html
> Correct minor grammar error in index.html

- worker/src/handlers/schedule.ts
For better readability and slight performance boost
> Replace else if with switch

- site/src/index.html
We estimate a 4th of our users opt-in to the analytics.
> third -> fourth
